## Een AI-oplossing bestaat uit drie elementen: data, model, interface

+-----------------------------+------------------------------------------------------------+----------------------------------------------------+------------------------------------+
| __Voorbeeld__               | __Data__                                                   | __Model patroon & soort__                          | __Interface__                      |
+=============================+============================================================+====================================================+====================================+
| Telefoon ontgrendelen       | Beelddata (gezicht)                                        | Herkenning (classificatie)                         | IPhone toegangsscherm              |
+-----------------------------+------------------------------------------------------------+----------------------------------------------------+------------------------------------+
| Slaapanalyse                | Sensordata (beweging, hartslag, ademhaling)                | Herkenning (classificatie)                         | Apple Watch, IPhone Gezondheid-app |
+-----------------------------+------------------------------------------------------------+----------------------------------------------------+------------------------------------+
| Gelezen tekst samenvatten   | Tekstdata                                                  | Mens-machine interactie                            | Notion app                         |
+-----------------------------+------------------------------------------------------------+----------------------------------------------------+------------------------------------+
| Drukte in de trein          | Check-ins/-outs, zitplaatscapaciteit, dienstregeling, etc. | Predictie (classificatie)                          | NS app                             |
+-----------------------------+------------------------------------------------------------+----------------------------------------------------+------------------------------------+
| OV-fiets beschikbaarheid    | Check-outs, OV-fiets capaciteit, stationskarakteristieken  | Predictie (regressie)                              | Website                            |
+-----------------------------+------------------------------------------------------------+----------------------------------------------------+------------------------------------+
| Geprioriteerde emails lezen | Tekstdata, email metadata                                  | Anomaliedetectie (classificatie)                   | Outlook                            |
+-----------------------------+------------------------------------------------------------+----------------------------------------------------+------------------------------------+
| Stofzuigerrobot aanzetten   | Sensordata, locatiedata, beelddata                         | Autonoom systeem                                   | iRobot app                         |
+-----------------------------+------------------------------------------------------------+----------------------------------------------------+------------------------------------+
| Dweilrobot configureren     | Sensordata, locatiedata, beelddata                         | Doel-georienteerd systeem (reinforcement learning) | iRobot app                         |
+-----------------------------+------------------------------------------------------------+----------------------------------------------------+------------------------------------+
| Aanbevolen jazz luisteren   | Gebruiksdata, voorkeuren                                   | Personalisatie (clustering)                        | Spotify app                        |
+-----------------------------+------------------------------------------------------------+----------------------------------------------------+------------------------------------+
| Fietsen vastleggen          | Sensordata (rotatie, hoek, hartslag), locatiedata (GPS)    | Herkenning (classificatie)                         | Apple watch                        |
+-----------------------------+------------------------------------------------------------+----------------------------------------------------+------------------------------------+